### Dockerfile-kamailio
FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y kamailio kamailio-extra-modules kamailio-sqlite-modules sqlite3 curl git && \
    apt-get clean

# Criação da estrutura de banco usando schema oficial
RUN mkdir -p /etc/kamailio/db

COPY init_db.sh /init_db.sh
RUN chmod +x /init_db.sh && /init_db.sh

COPY kamailio/kamailio.cfg /etc/kamailio/kamailio.cfg

CMD ["kamailio", "-DD", "-E"]

